export const db = [
  {
    name: "Football Standings",
    imageURL: "assets/images/football-standings.png",
    stack: "angular",
    viewLink: "https://football-standingss.netlify.app/",
    repoLink: "https://github.com/lawaldare/football-standing",
    desc: "This is a app that shows the football standings of 4 popular leagues. Built with Angular 16 and implemented with Angular signals",
  },
  {
    name: "Crypto Assets",
    imageURL: "assets/images/ecabs.png",
    stack: "angular",
    viewLink: "https://crypto-assets-ecabs.netlify.app/",
    repoLink: "https://github.com/lawaldare/crypto-assets-ecab",
    desc: "This is a app that shows all crypto assests built with Angular and using Ngrx for state management",
  },
  {
    name: "Ecommerce",
    imageURL: "assets/images/ecommerce.png",
    stack: "angular",
    viewLink: "https://ecommerce-ngrx.netlify.app/",
    repoLink: "https://github.com/lawaldare/ecommerce-angular-ngrx",
    desc: "This is a amazon-theme-like ecommerce application built with Angular and using Ngrx for state management",
  },
  {
    name: "YouTube Trending Videos",
    imageURL: "assets/images/youtube.png",
    stack: "angular",
    viewLink: "https://yt-trending.netlify.app/",
    repoLink: "https://github.com/lawaldare/youtube-trending-video-repo",
    desc: "This app enable users to view the Youtube trending videos of another countries apart from their country. It is built with angular 16 and uses signals",
  },
  {
    name: "Countries With Themes",
    imageURL: "assets/images/countries.png",
    stack: "angular",
    viewLink: "https://countries-with-theme-switch.netlify.com",
    repoLink: "https://github.com/lawaldare/countries-theme-switch",
    desc: "The app shows over 250 countries with their details and enable user to switch from dark mode to light mode and also to search and filter by region.",
  },
  {
    name: "Clock",
    imageURL: "assets/images/clock.jpg",
    stack: "javascript",
    viewLink: "https://lawaldare.github.io/clock/",
    repoLink: "https://github.com/lawaldare/clock",
    desc: "The app shows a real time clock.",
  },
  {
    name: "ThreeJS Animation",
    imageURL: "assets/images/animation.png",
    stack: "animation",
    viewLink: "https://threejs-portfolio-homepage.netlify.app/",
    repoLink: "https://threejs-portfolio-homepage.netlify.app/",
    desc: "This is a simple animation using threejs and WebGL",
  },
  {
    name: "Expense Tracker",
    imageURL: "assets/images/expense-tracker.png",
    stack: "angular",
    viewLink: "https://expense-tracker-angular.netlify.com/",
    repoLink: "https://github.com/lawaldare/expenseTracker",
    desc: "The app is used to calculate the expense and income of user",
  },
  {
    name: "Neumorphic Calculator",
    imageURL: "assets/images/calculator.png",
    stack: "javascript",
    viewLink: "https://lawaldare.github.io/neumorphic-calculator/",
    repoLink: "https://github.com/lawaldare/neumorphic-calculator",
    desc: "This is a calculator built with Neumorphic designs",
  },
  {
    name: "Mentor Coven",
    imageURL: "assets/images/mentor.jpg",
    stack: "javascript",
    viewLink: "https://mentor-coven.netlify.app/",
    repoLink: "https://mentor-coven.netlify.app/",
    desc: "This is a landng page for a mentorship website",
  },
  {
    name: "College Website",
    imageURL: "assets/images/college.png",
    stack: "javascript",
    viewLink: "https://lawaldare.github.io/college-website/",
    repoLink: "https://github.com/lawaldare/college-website",
    desc: "This is a landng page for a college website",
  },
  // {
  //   name: 'Octotasker LLC',
  //   imageURL: 'assets/images/octotasker.png',
  //   stack: 'wordpress',
  //   viewLink: 'https://octotasker.com/',
  //   repoLink: 'https://octotasker.com/',
  //   desc: 'This is a website for an Agency',
  // },
  {
    name: "Bookstore",
    imageURL: "assets/images/bookstore.png",
    stack: "angular",
    viewLink: "https://bookstore-dare.netlify.com/",
    repoLink: "https://github.com/lawaldare/bookstore-angular",
    desc: "The app allows user to search for books online from google books store.",
  },
  {
    name: "Client Panel",
    imageURL: "assets/images/clientpanel.jpg",
    stack: "angular",
    viewLink: "https://client-panel-2020.netlify.app/",
    repoLink: "https://github.com/lawaldare/client-panel",
    desc: "This is a fullstack solution with firebase as backend and Angular as frontend. It is a dashboard for debtors.",
  },
  // {
  //   name: 'Naira Converter',
  //   imageURL: 'assets/images/naira-converter.jpg',
  //   stack: 'javascript',
  //   viewLink: 'https://lawaldare.github.io/naira-converter/',
  //   repoLink: 'https://github.com/lawaldare/naira-converter',
  //   desc: 'The app enable users to convert their Naira money to US Dollars, UK Pounds and Euros with a current exchange rate.'
  // },
  {
    name: "Weather App",
    imageURL: "assets/images/weather.png",
    stack: "angular",
    viewLink: "https://da-weather.netlify.com/",
    repoLink: "https://github.com/lawaldare/weather",
    desc: "This app enable users to see the current weather of any city in the world",
  },
  {
    name: "Color game",
    imageURL: "assets/images/color-game.jpg",
    stack: "javascript",
    viewLink: "https://lawaldare.github.io/color-game/",
    repoLink: "https://github.com/lawaldare/color-game",
    desc: "This game app enable users to pick the color randomly displayed in RGB. It has two levels of difficulty, easy and hard.",
  },
  {
    name: "Mealy App",
    imageURL: "assets/images/mealy.png",
    stack: "angular",
    viewLink: "https://mealy.netlify.com/",
    repoLink: "https://github.com/lawaldare/meal-angular-repo",
    desc: "This app helps users to be a good. It randomly gives them a meal, history about the meal, its ingredients and a video on how to prepare it.",
  },
  {
    name: "Train With Talia",
    imageURL: "assets/images/trainwithtalia.jpg",
    stack: "wordpress",
    viewLink: "https://trainwithtalia.com/",
    repoLink: "https://trainwithtalia.com/",
    desc: "This is a website for physical fitness based in California, USA. It is owned by Talia Adams.",
  },
  {
    name: "Data Info",
    imageURL: "assets/images/data-info.png",
    stack: "angular",
    viewLink: "https://data-info-2022.web.app/",
    repoLink: "https://github.com/lawaldare/data-info",
    desc: "This is a project that make use of jsonplaceholder data and display them with filtering and pagination functionality",
  },
  {
    name: "Data Warehouse",
    imageURL: "assets/images/data-warehouse.png",
    stack: "javascript",
    viewLink: "https://data-warehouse-2021.netlify.app/",
    repoLink: "https://github.com/lawaldare/data-warehouse",
    desc: "This is a landing page of a data warehouse company",
  },
  {
    name: "Bitcoin Calculator",
    imageURL: "assets/images/bitcoin.png",
    stack: "angular",
    viewLink: "https://bitcoin-calculator.netlify.app/",
    repoLink: "https://github.com/lawaldare/bitcoin-angular",
    desc: "This app enable users dealing with bitcoin to know their current status, either they are making profit or they are not.",
  },
  {
    name: "Github",
    imageURL: "assets/images/github.png",
    stack: "angular",
    viewLink: "https://github-app.netlify.com/",
    repoLink: "https://github.com/lawaldare/github-search-angular",
    desc: "This app enable users to easily search for a github account via the username and it gives some vital information about the account. Also, user can view the followers of the account.",
  },
  {
    name: "Shortly",
    imageURL: "assets/images/shortly.png",
    stack: "angular",
    viewLink: "https://link-shorter.netlify.com/",
    repoLink: "https://github.com/lawaldare/shortly",
    desc: "This app enable users to easily shorten their long Urls with a hashed keys.",
  },
  // {
  //   name: 'Slapdick Bullies',
  //   imageURL: 'assets/images/slapdick.png',
  //   stack: 'wordpress',
  //   viewLink: 'https://slapdickbullies.com/',
  //   repoLink: 'https://slapdickbullies.com/',
  //   desc: 'This is a website for selling dogs'
  // },
  {
    name: "PJ Confidential",
    imageURL: "assets/images/pjconfidential.png",
    stack: "wordpress",
    viewLink: "https://pjconfidential.com/",
    repoLink: "https://pjconfidential.com/",
    desc: "This is an ecommerce website",
  },
];

export const jobs = [
  {
    title: "Frontend Engineer",
    companyName: "European Bioinformatics Institute | EMBL-EBI",
    location: "Cambridge, United Kingdom",
    date: "June, 2024 - Present",
    themeColor: "#7b68ee",
  },
  {
    title: "Senior Frontend Engineer",
    companyName: "EPG Financial Services Ltd",
    location: "Sliema, Malta",
    date: "April, 2024 - June, 2024",
    themeColor: "#fd71af",
  },
  {
    title: "Frontend Engineer",
    companyName: "Betsson Group",
    location: "Ta`Xbiex, Malta",
    date: "July, 2023 - April, 2024",
    themeColor: "#00b884",
  },
  {
    title: "Frontend Engineer",
    companyName: "Origin Markets",
    location: "London, United Kingdom",
    date: "March, 2022 - June, 2023",
    themeColor: "#7b68ee",
  },
  {
    title: "Frontend Engineer",
    companyName: "Code & Care",
    location: "Kharkiv, Ukraine",
    date: "September, 2021 - March, 2022",
    themeColor: "#fd7171",
  },
  {
    title: "Frontend Engineer",
    companyName: "Renmoney MFB",
    location: "Lagos, Nigeria",
    date: "March, 2020 - March, 2022",
    themeColor: "#49ccf9",
  },
  {
    title: "Frontend Engineer",
    companyName: "Tr1pp",
    location: "London, United Kingdom",
    date: "July, 2021 - November, 2021",
    themeColor: "#fd71af",
  },
  {
    title: "Wordpress Developer",
    companyName: "NXT Factor",
    location: "New York, USA",
    date: "October, 2019 - June, 2021",
    themeColor: "#ffc800",
  },
  {
    title: "WordPress Developer",
    companyName: "Midland Digital Solutions",
    location: "Lagos, Nigeria",
    date: "August, 2020 - December, 2020",
    themeColor: "#00b884",
  },
  {
    title: "Frontend Engineer",
    companyName: "Terragon Group",
    location: "Lagos, Nigeria",
    date: "June, 2019 - February, 2020",
    themeColor: "#fd7171",
  },
  {
    title: "Math Tutor",
    companyName: "Phoebestar Royalty Schools",
    location: "Osogbo, Nigeria",
    date: "October 2014 - July 2018",
    themeColor: "#49ccf9",
  },
];

export const contactIcons = [
  {
    link: "https://www.facebook.com/lawal.dare",
    icon: "fab fa-facebook-square",
  },
  {
    link: "https://twitter.com/lawaldarekayode",
    icon: "fab fa-twitter-square",
  },
  {
    link: "https://www.linkedin.com/in/dare-lawal/",
    icon: "fab fa-linkedin",
  },
  {
    link: "https://github.com/lawaldare",
    icon: "fab fa-github-square",
  },
  {
    link: "mailto:lawaldare@gmail.com",
    icon: "fas fa-envelope",
  },
  {
    link: "tel:+2349051450310",
    icon: "fas fa-phone",
  },
  {
    link: "https://www.instagram.com/lawaldarekayode/",
    icon: "fab fa-instagram",
  },
];
